### ISSUE TITLE
Website Unavailable

### ISSUE THREAD

**Issue by DREWNOLT** [openly-group/Openly#5]
For some reason, the website is not accessible, and the repl just keeps buffering. Anyone know why?

**Comment by wgyt** [comment]
Bro, the site is up. https://openly.meower.org

**Comment by DREWNOLT** [comment]
no, openly.tk

**Comment by wgyt** [comment]
> no, openly.tk

well yeah, no one knows who owns it

btw use the discord ( https://discord.gg/W5YNBamuub)
